{% set name = "intersphinx-registry" %}
{% set version = "0.2510.17" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/intersphinx_registry-{{ version }}.tar.gz
  sha256: 448e710d023a717ea8d227ebf5f0834c7c31d357846b2b2397d2b8c50e65fc83

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - flit-core >=3.2,<4
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - intersphinx_registry
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/Carreau/intersphinx_registry
  summary: This package provides convenient utilities and data to write a sphinx config file.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - larsoner
    - Carreau
