{% set name = "intersphinx-registry" %}
{% set version = "0.2601.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/intersphinx_registry-{{ version }}.tar.gz
  sha256: bc6db16646e5406720c43e7ab51e9c7db1fd7c5e017ce437531c2d4b87e20a07

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - flit-core >=3.2,<4
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - intersphinx_registry
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/Carreau/intersphinx_registry
  summary: This package provides convenient utilities and data to write a sphinx config file.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - larsoner
    - Carreau
